---
title: Placeholder Magazine
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: ''
    layout: post
    author: ''
    description: ''
    author-block: 'false'
    author-image: ''
    author-bio: ''
- scope:
    path: ''
    type: pages
  values:
    image: ''
    layout: page
email: andrewhemans@gmail.com
description: Placeholder Magazine is a fiercely independent critical voice covering
  contemporary arts, culture, and literature. We are a Central Valley-based not-for-profit
  arts organization led entirely by volunteers.
baseurl: 
url: www.placeholdermag.com
twitter_username: PlaceholderMag
github_username: andrewhemans
markdown: kramdown
