---
title: Placeholder!
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    author: ''
    image: ''
email: andrewhemans@gmail.com
description: 
baseurl: 
url: 
twitter_username: PlaceholderMag
github_username: andrewhemans
markdown: kramdown
