---
title: Placeholder Magazine
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: ''
    layout: post
    author: ''
    description: ''
    author-block: 'false'
    author-image: ''
    author-bio: ''
- scope:
    path: ''
    type: products
  values:
    layout: store
    permalink: "/store/:title/"
    name: ''
    price: 0.0
    image: ''
- scope:
    path: ''
    type: pages
  values:
    image: ''
    layout: page
snipcart_api_key: YjE0ZDQ3ZWMtZDJlNi00MDk0LWJmNGYtOTk2NTEyMzkyNTBhNjM2MjAxMjI3ODUxNTM1MzQw
email: placeholdermag@gmail.com
description: A fiercely independent critical voice covering contemporary arts, culture
  and literature magazine featuring emerging creatives with featured articles, blogs,
  video, and more.
baseurl: 
url: www.placeholdermag.com
twitter_username: PlaceholderMag
github_username: andrewhemans
markdown: kramdown
