---
title: Placeholder!
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    author: ''
    image: ''
    featured: ''
    layout: post
- scope:
    path: ''
    type: pages
  values:
    image: ''
    layout: page
email: andrewhemans@gmail.com
description:
baseurl:
url: www.placeholdermagazine.com
twitter_username: PlaceholderMag
github_username: andrewhemans
markdown: kramdown
